[package]
name = "nbt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
thiserror = "1.0.38"
common = { path = "../common" }
tracing = "0.1.37"
