[package]
name = "mirai-repl"
version = "0.1.0"
edition = "2021"

[dependencies]
proto = { package = "mirai-proto", path = "../proto" }
util = { package = "mirai-util", path = "../util" }

anyhow = "1.0.80"
tracing = "0.1.40"
fred = "8.0.2"
